### ISSUE TITLE
Support for MCP2003B?

### ISSUE THREAD

**Issue by wallem89** [zpg6/mcp2003a#1]
Does this crate also support the newer B variant of the MCP2003 soon?

I see that the MCP2003A is not recommended for new designs but the MCP2003B is.

In the [TB3150 - MCP2003A to MCP2003B Migration]( https://ww1.microchip.com/downloads/en/DeviceDoc/90003150A.pdf) I read that there are some difference which has impact on a the circuit but I guess not on the driver.

**Comment by zpg6** [comment]
Hi @wallem89 :

[MCP2003/4/3A/4A Datasheet](https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/DataSheets/20002230G.pdf) was used as reference for this project - and I have also verified it works on MCP2003E as well.

While I haven't had a chance to test it on MCP2003B, looking at the [MCP2003B Datasheet](https://ww1.microchip.com/downloads/en/DeviceDoc/2000546C3.pdf) the only difference popping out to me is the extended temperature range. Let me know if it ends up working for you, or I will reply to this again when I get a chance to test it myself.

---

## Edit:

I found same [Migration guide from MCP2003A to MCP2003B](https://ww1.microchip.com/downloads/en/DeviceDoc/90003150A.pdf) which you had mentioned but I missed.

> The MCP2003B can be used as a drop-in replacement for the MCP2003A. Although there are no functional
differences in using the MCP2003B over the MCP2003A, the enhancements described in Table 1 should be considered.

Since Microchip advertises as a functional drop-in replacement, I will update the README soon to reflect this.
